app/posts/forms.py
from wtforms import StringField, TextAreaField, ValidationError
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm
from app.models import Post, slugify


class PostForm(FlaskForm):
    title = StringField('Title', validators=(DataRequired(),))
    body = TextAreaField('Body', validators=(DataRequired(),))

    def validate_title(self, title):
        slug = Post.query.filter_by(slug=slugify(title.data)).first()
        if slug is not None:
            raise ValidationError('Please use different titles')

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask_login import login_required, current_user

from app.models import Post, Tag, slugify
from .forms import PostForm
from app import db
from app import app

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=('GET', 'POST'))
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        try:
            post = Post(title=form.title.data, body=form.body.data, user_id=current_user.id)
            db.session.add(post)
            db.session.commit()
        except:
            flash('Something went wrong')
            return render_template('posts/create_post.html', form=form)

        return redirect(url_for('posts.post_detail', slug=post.slug))
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=('GET', 'POST'))
@login_required
def edit_post(slug):
    post = Post.query.filter((Post.slug == slug) & (Post.user_id == current_user.id)).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    followed_posts = request.args.get('followed_posts', 0, type=int)
    posts = Post.query
    if current_user.is_authenticated and followed_posts == 1:
        posts = current_user.followed_posts()
    if q:
        posts = posts.filter(Post.title.contains(q) | Post.body.contains(q))
    posts = posts.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag, posts=tag.posts)

app/posts/templates/posts/_post.html
<table>
    <tr>
        <td valign="middle"><img src="{{ post.author.avatar(64) }}"></td>
        <td>
            <figure>
                <blockquote class="blockquote">
                    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
                </blockquote>
                <figcaption class="blockquote-footer">
                Created {{ moment(post.created).format('LLL') }} by
                <a href="{{ url_for('users', username=post.author.username) }}">
                    <i>{{ post.author.username }}</i>
                </a>
                </figcaption>
            </figure>
        </td>
    </tr>
</table>

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
Create new post
{% endblock %}

{% block content_title %}
New post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label(class='form-label')}}
            {{ form.title(class='form-control')}}
        </p>
        <p>
            {{ form.body.label(class='form-label')}}
            {{ form.body(class='form-control')}}
        </p>
        <div class="mb-3">
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    </form>
</div>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
Edit post
{% endblock %}

{% block content_title %}
Edit post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label(class='form-label')}}
            {{ form.title(class='form-control')}}
        </p>
        <p>
            {{ form.body.label(class='form-label')}}
            {{ form.body(class='form-control')}}
        </p>
        <div class="mb-3">
            <button type="submit" class="btn btn-success">Edit</button>
        </div>
    </form>
</div>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Blueprint
{% endblock %}

{% block content_title %}
<a class="text-dark" href="./">All posts</a> | <a class="text-dark" href="./?followed_posts=1">Followed posts</a>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        {% for post in pages.items %}
            {% include 'posts/_post.html' %}
        {% endfor %}
        {% for i in range(pages.per_page - pages.items|length) %}
            <p><br></p>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item {% if not pages.has_prev %}} disabled {% endif %}">
                    <a class="page-link" href="./?page={{pages.prev_num}}{% if request.args.get('q') %}&q={{request.args['q']}}{% endif %}{% if request.args.get('followed_posts') %}&followed_posts={{request.args['followed_posts']}}{% endif %}">Previous</a>
                </li>
                {% for page in pages.iter_pages() %}
                    <li class="page-item {% if page == pages.page %}active{% endif %}">
                        <a class="page-link" href="./?page={{ page }}{% if request.args.get('q') %}&q={{request.args['q']}}{% endif %}{% if request.args.get('followed_posts') %}&followed_posts={{request.args['followed_posts']}}{% endif %}">{{page}}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not pages.has_next %}} disabled {% endif %}">
                    <a class="page-link" href="./?page={{pages.next_num}}{% if request.args.get('q') %}&q={{request.args['q']}}{% endif %}{% if request.args.get('followed_posts') %}&followed_posts={{request.args['followed_posts']}}{% endif %}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="col">
        <form action="{{ url_for('posts.create_post')}}" method='GET'>
            <button type="submit" class="btn btn-primary btn-lg">New post</button>
        </form>
    </div>
</div>


{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content_title %}
    {{post.title}}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div>
            {% for tag in post.tags%}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge bg-info text-dark">{{tag.name}}</span></a>
            {% endfor %}
        </div>
        <figure>
            <blockquote class="blockquote">
                <p>{{ post.body }}</p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Created at {{ post.created.strftime('%d %B %Y in %H:%M') }} by
                <a href="{{ url_for('users', username=post.author.username) }}">
                    <i>{{ post.author.username }}</i>
                </a>
            </figcaption>
        </figure>
    </div>
    {% if post.user_id == current_user.id %}
    <div class="col">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method='GET'>
            <button type="submit" class="btn btn-primary btn-lg">Edit post</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{tag.name}} posts
{% endblock %}

{% block content_title %}
    Posts for "{{tag.name}}" tag:
{% endblock %}

{% block content %}
    {% for post in posts%}
    <p>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a>
    </p>
    {% endfor %}
{% endblock %}