app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask_login import login_required, current_user

from app.models import Post, Tag, slugify
from .forms import PostForm
from app import db
from app import app

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=('GET', 'POST'))
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        try:
            post = Post(title=form.title.data, body=form.body.data, user_id=current_user.id)
            db.session.add(post)
            db.session.commit()
        except:
            flash('Something went wrong')
            return render_template('posts/create_post.html', form=form)

        return redirect(url_for('posts.post_detail', slug=post.slug))
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=('GET', 'POST'))
@login_required
def edit_post(slug):
    post = Post.query.filter((Post.slug == slug) & (Post.user_id == current_user.id)).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    followed_posts = request.args.get('followed_posts', 0, type=int)
    posts = Post.query
    if current_user.is_authenticated and followed_posts == 1:
        posts = current_user.followed_posts()
    if q:
        posts = posts.filter(Post.title.contains(q) | Post.body.contains(q))
    posts = posts.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])
    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag, posts=tag.posts)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %} | Flask app
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {{ moment.include_moment() }}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href=" {{ url_for('index') }} ">Blackjack</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href=" {{ url_for('index') }} ">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {{ url_for('posts.index') }} ">Blog</a>
                </li>
            </ul>
            <form class="d-flex" method="GET">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-success me-2" type="submit">Search</button>
            </form>
            <ul class="navbar-nav me-2">
                {% if current_user.is_anonymous %}
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="{{ url_for('login') }}">Login</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-outline-danger" href="{{ url_for('logout') }}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('users', username=current_user.username) }}">Profile</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="mt-2">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>


    <div class="row">
        <h1>
            {% block content_title %}
            {% endblock %}
        </h1>
    </div>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}
    {{ current_user.username }} | Edit profile
{% endblock %}

{% block content_title %}
    {{ current_user.username }} | Edit profile
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label(class='form-label') }}
            {{ form.username(class='form-control') }}
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label(class='form-label') }}
            {{ form.about_me(class='form-control', rows=4) }}
            {% for error in form.about_me.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <div class="mb-3">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Index page
{% endblock %}

{% block content %}
    Some content
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content_title %}
    Sign in
{% endblock %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label(class='form-label') }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label(class='form-label') }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
        <p>
            Forgot your password?
            <a href="{{ url_for('reset_password_request') }}">Click to reset it</a>
        </p>
    </form>
<p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content_title %}
    Sign in
{% endblock %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label(class='form-label') }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label(class='form-label') }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{error}}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label(class='form-label') }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.repeat_password.label(class='form-label') }}<br>
            {{ form.repeat_password(size=32) }}<br>
            {% for error in form.repeat_password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/reset_password.html
{% extends 'base.html' %}

{% block title %}
    Reset Your Password
{% endblock %}

{% block content_title %}
    Reset Your Password
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/reset_password_request.html
{% extends 'base.html' %}

{% block title %}
    Reset Password
{% endblock %}

{% block content_title %}
    Reset Password
{% endblock %}


{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block content %}
    <div class="row mb-5">
        <div class="col">
            <table>
                <tr>
                    <td valign="top"><img src="{{ user.avatar(128) }}"></td>
                    <td class="ml-1">
                        <h1>User: {{ user.username }}</h1>
                        <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
                        {% if user.last_seen %}<p>Last seen: {{ moment(user.last_seen).fromNow() }}</p>{% endif %}
                        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="col">
            {% if current_user.username == user.username %}
            <form action="{{ url_for('edit_profile', username=current_user.username)}}" method='GET'>
                <button type="submit" class="btn btn-primary btn-lg">Edit profile</button>
            </form>
            {% elif current_user.is_following(user) %}
            <form action="{{ url_for('unfollow', username=user.username)}}" method='GET'>
                <button type="submit" class="btn btn-secondary btn-lg">Unfollow</button>
            </form>
            {% else %}
            <form action="{{ url_for('follow', username=user.username)}}" method='GET'>
                <button type="submit" class="btn btn-primary btn-lg">Follow</button>
            </form>
            {% endif %}
        </div>
    </div>

    {% for post in posts %}
        {% include 'posts/_post.html' %}
    {% endfor %}
{% endblock %}